# Generated by Django 5.2.4 on 2025-09-17 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lightning_endpoint', models.URLField(help_text='URL del endpoint de Lightning AI')),
                ('api_key', models.CharField(help_text='API Key para autenticación', max_length=200)),
                ('model_name', models.CharField(default='google/gemma-3-4b-it', max_length=100)),
                ('max_tokens_default', models.IntegerField(default=256)),
                ('temperature_default', models.FloatField(default=0.7)),
                ('timeout_seconds', models.IntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('product_description', 'Descripción de Producto'), ('image_analysis', 'Análisis de Imagen'), ('text_generation', 'Generación de Texto'), ('chat', 'Chat Conversacional')], default='chat', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=10)),
                ('prompt', models.TextField(help_text='Prompt o texto enviado al modelo')),
                ('image_urls', models.JSONField(blank=True, default=list, help_text='URLs de imágenes enviadas')),
                ('model_name', models.CharField(default='google/gemma-3-4b-it', max_length=100)),
                ('max_tokens', models.IntegerField(default=256)),
                ('temperature', models.FloatField(default=0.7)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('response_tokens', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0, help_text='Tiempo de procesamiento en segundos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Request',
                'verbose_name_plural': 'AI Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAIGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('title', 'Título'), ('description', 'Descripción'), ('tags', 'Tags'), ('category_suggestion', 'Sugerencia de Categoría'), ('price_suggestion', 'Sugerencia de Precio')], max_length=50)),
                ('original_content', models.TextField(blank=True, help_text='Contenido original antes de la IA')),
                ('ai_generated_content', models.TextField(help_text='Contenido generado por IA')),
                ('is_approved', models.BooleanField(default=False, help_text='Si el usuario aprobó usar el contenido generado')),
                ('is_used', models.BooleanField(default=False, help_text='Si el contenido se aplicó al producto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ai_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_API.airequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='products.product')),
            ],
            options={
                'verbose_name': 'Product AI Generation',
                'verbose_name_plural': 'Product AI Generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('product_description_requests', models.IntegerField(default=0)),
                ('image_analysis_requests', models.IntegerField(default=0)),
                ('text_generation_requests', models.IntegerField(default=0)),
                ('chat_requests', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Stats',
                'verbose_name_plural': 'AI Usage Stats',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
