# Generated by Django 5.2.4 on 2025-09-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaigeneration',
            name='ai_request',
        ),
        migrations.RemoveField(
            model_name='productaigeneration',
            name='product',
        ),
        migrations.DeleteModel(
            name='AIUsageStats',
        ),
        migrations.DeleteModel(
            name='ProductAIGeneration',
        ),
    ]
