# Generated by Django 5.2.4 on 2025-09-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_tag_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='Borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
